[package]
name = "textual"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
futures-time = "3.0.1"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
