[package]
name = "textual"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tcss.workspace = true
log.workspace = true

thiserror.workspace = true
crossterm.workspace = true
tokio.workspace = true
futures.workspace = true

[dev-dependencies]
# Enable test-util for deterministic virtual time testing
tokio = { version = "1.0", features = ["test-util"] }
